# Generated by Django 4.2.3 on 2023-10-19 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0002_funcionario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
    ]
