# Generated by Django 4.2.5 on 2023-10-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0004_alimentacao_mensalidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nome',
            field=models.CharField(default='Nome Padrão', max_length=100),
        ),
    ]
